server:
  port: 9002
spring:
  application:
    name: hrm-course
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hrm_course
        username: root
        password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true